name: Keep Alive

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Stride Health Check
        run: curl -X GET https://stride-full-stack.vercel.app/api/health
